# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jonek/repos/TIN

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jonek/repos/TIN

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonek/repos/TIN/CMakeFiles /home/jonek/repos/TIN/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonek/repos/TIN/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DETECTOR

# Build rule for target.
DETECTOR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DETECTOR
.PHONY : DETECTOR

# fast build rule for target.
DETECTOR/fast:
	$(MAKE) -f CMakeFiles/DETECTOR.dir/build.make CMakeFiles/DETECTOR.dir/build
.PHONY : DETECTOR/fast

#=============================================================================
# Target rules for targets named MANAGER

# Build rule for target.
MANAGER: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MANAGER
.PHONY : MANAGER

# fast build rule for target.
MANAGER/fast:
	$(MAKE) -f CMakeFiles/MANAGER.dir/build.make CMakeFiles/MANAGER.dir/build
.PHONY : MANAGER/fast

detector/client.o: detector/client.c.o
.PHONY : detector/client.o

# target to build an object file
detector/client.c.o:
	$(MAKE) -f CMakeFiles/MANAGER.dir/build.make CMakeFiles/MANAGER.dir/detector/client.c.o
.PHONY : detector/client.c.o

detector/client.i: detector/client.c.i
.PHONY : detector/client.i

# target to preprocess a source file
detector/client.c.i:
	$(MAKE) -f CMakeFiles/MANAGER.dir/build.make CMakeFiles/MANAGER.dir/detector/client.c.i
.PHONY : detector/client.c.i

detector/client.s: detector/client.c.s
.PHONY : detector/client.s

# target to generate assembly for a file
detector/client.c.s:
	$(MAKE) -f CMakeFiles/MANAGER.dir/build.make CMakeFiles/MANAGER.dir/detector/client.c.s
.PHONY : detector/client.c.s

manager/server.o: manager/server.c.o
.PHONY : manager/server.o

# target to build an object file
manager/server.c.o:
	$(MAKE) -f CMakeFiles/DETECTOR.dir/build.make CMakeFiles/DETECTOR.dir/manager/server.c.o
.PHONY : manager/server.c.o

manager/server.i: manager/server.c.i
.PHONY : manager/server.i

# target to preprocess a source file
manager/server.c.i:
	$(MAKE) -f CMakeFiles/DETECTOR.dir/build.make CMakeFiles/DETECTOR.dir/manager/server.c.i
.PHONY : manager/server.c.i

manager/server.s: manager/server.c.s
.PHONY : manager/server.s

# target to generate assembly for a file
manager/server.c.s:
	$(MAKE) -f CMakeFiles/DETECTOR.dir/build.make CMakeFiles/DETECTOR.dir/manager/server.c.s
.PHONY : manager/server.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DETECTOR"
	@echo "... MANAGER"
	@echo "... detector/client.o"
	@echo "... detector/client.i"
	@echo "... detector/client.s"
	@echo "... manager/server.o"
	@echo "... manager/server.i"
	@echo "... manager/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

