#ifndef TEST_MESSAGETYPE_H
#define TEST_MESSAGETYPE_H

enum messageType {
    REPORT,
    ALARM,
    INFINITY_RESISTANCE,
    CHANGE_TYPICAL_RESISTANCE,
    CHECK_STATE
};

#endif //TEST_MESSAGETYPE_H
